#%RAML 1.0
title: cep

/cep:
  get:
    displayName: 
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    queryParameters:
      cep:
        type: string
        example: "05001200"
    responses:
      200:
        body:
          application/json:
            type: array
